---
title: "ParetoTI Application of MATLAB-derived Archetypes"
author: "Sarah Groves"
date: "06/18/2021"
output:
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: inline
---

```{r setup include=FALSE}
library(ParetoTI)
# set random seed
set.seed(4355)
# generate archetype positions
archetypes = generate_arc(arc_coord = list(c(5, 0, 4), c(-10, 15, 0), c(-30, -20, -5)),
                          mean = 0, sd = 1)
# generate 1000 data points that are a convex combination (weighted sum) of archetypes
data = generate_data(archetypes$XC, N_examples = 1e3, jiiter = 0.04, size = 0.99)
colnames(data) = paste0("cell", seq_len(ncol(data)))

# plot
plot_arc(arc_data = archetypes, data = data,
         which_dimensions = 1:2) + ylim(-19, 17) +
  ggtitle("Ground truth archetypes")

```

```{r}
wd <- '/Users/smgroves/Dropbox (VU Basic Sciences)/SCLC/RNAseq-analysis/WGCNA-analysis'
d <- read.table('/Users/smgroves/Dropbox (VU Basic Sciences)/SCLC_data/airway_epithelium/trachea_10x_log2TPM.txt',
                 as.is=TRUE, sep='\t', header=TRUE, row.names=1)
# qn <- normalize.quantiles(as.matrix(d))
# dimnames(qn) <- dimnames(d)
# d <- apply(qn,c(1,2), log2)
ne <- d[,row.names(phenotypes[phenotypes$cluster == "Neuroendocrine",])]

lag <- apply(ne,1,function(x) all(x < 3))
ne <- ne[!lag,]
gsg = goodSamplesGenes(d, verbose = 3);
if (!gsg$allOK)
{
# Optionally, print the gene and sample names that were removed:
if (sum(!gsg$goodGenes)>0)
printFlush(paste("Removing genes:", paste(names(datExpr0)[!gsg$goodGenes], collapse = ", ")));
if (sum(!gsg$goodSamples)>0)
printFlush(paste("Removing samples:", paste(rownames(datExpr0)[!gsg$goodSamples], collapse = ", ")));
# Remove the offending genes and samples from the data:
d = d[gsg$goodSamples, gsg$goodGenes]
}

gev <- t(ne)
```

```{r}
# Load package
library(ParetoTI)
# If package does not load because "py_pcha is not found" make sure you do not have
# a python environment already loaded in this R session (e.g. restart R and try loading again).

# Install python dependencies (like py_pcha) into python conda environment,
# and (optionally) install *extra_packages*.
ParetoTI::install_py_pcha(method = "virtualenv")
reticulate::use_condaenv("reticulate_PCHA", conda = "auto",
                         required = TRUE) # set TRUE to force R to use reticulate_PCHA
arc_data = fit_pch(gev, noc = as.integer(5), delta = 0)

reticulate::py_discover_config("py_pcha")
```

